# Generated by Django 4.2.9 on 2024-02-05 14:26

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("apps_reobjects", "0010_coordinates"),
        ("apps_admin_objects", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="CoordinatesProxy",
            fields=[],
            options={
                "verbose_name": "Координаты",
                "verbose_name_plural": "Координаты",
                "proxy": True,
                "indexes": [],
                "constraints": [],
            },
            bases=("apps_reobjects.coordinates",),
        ),
    ]
