# Generated by Django 4.2.9 on 2024-02-05 15:16

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("apps_admin_objects", "0002_coordinatesproxy"),
    ]

    operations = [
        migrations.DeleteModel(
            name="CoordinatesProxy",
        ),
    ]
