# Generated by Django 4.2.9 on 2024-02-08 14:07

from django.db import migrations


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("apps_village", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="VillageProxy",
            fields=[],
            options={
                "verbose_name": "Поселок",
                "verbose_name_plural": "Поселки",
                "proxy": True,
                "indexes": [],
                "constraints": [],
            },
            bases=("apps_village.village",),
        ),
    ]
