# Generated by Django 4.2.9 on 2024-01-28 13:24

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):
    dependencies = [
        ("apps_reobjects", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Category",
            fields=[
                (
                    "uuid",
                    models.UUIDField(
                        default=uuid.uuid4, primary_key=True, serialize=False
                    ),
                ),
                ("name", models.CharField(blank=True, max_length=100)),
            ],
            options={
                "verbose_name": "Категория объекта",
                "verbose_name_plural": "Категория объекта",
            },
        ),
        migrations.CreateModel(
            name="EngineeringServices",
            fields=[
                (
                    "uuid",
                    models.UUIDField(
                        default=uuid.uuid4, primary_key=True, serialize=False
                    ),
                ),
                (
                    "value",
                    models.CharField(
                        blank=True,
                        help_text="Наличие инженерных сетей",
                        max_length=50,
                        verbose_name="Инженерные сети",
                    ),
                ),
            ],
            options={
                "verbose_name": "Инженерные сети",
                "verbose_name_plural": "Инженерные сети",
            },
        ),
        migrations.CreateModel(
            name="Fencing",
            fields=[
                (
                    "uuid",
                    models.UUIDField(
                        default=uuid.uuid4, primary_key=True, serialize=False
                    ),
                ),
                (
                    "value",
                    models.CharField(
                        blank=True,
                        help_text="Ограждение участка",
                        max_length=50,
                        verbose_name="Ограждение участка",
                    ),
                ),
            ],
            options={
                "verbose_name": "Ограждение участка",
                "verbose_name_plural": "Ограждение участка",
            },
        ),
        migrations.CreateModel(
            name="Foundation",
            fields=[
                (
                    "uuid",
                    models.UUIDField(
                        default=uuid.uuid4, primary_key=True, serialize=False
                    ),
                ),
                (
                    "value",
                    models.CharField(
                        blank=True,
                        help_text="Тип фундамента",
                        max_length=50,
                        verbose_name="Тип фундамента",
                    ),
                ),
            ],
            options={
                "verbose_name": "Тип фундамента",
                "verbose_name_plural": "Тип фундамента",
            },
        ),
        migrations.CreateModel(
            name="LandCategory",
            fields=[
                (
                    "uuid",
                    models.UUIDField(
                        default=uuid.uuid4, primary_key=True, serialize=False
                    ),
                ),
                (
                    "value",
                    models.CharField(
                        blank=True,
                        help_text="Категория земли",
                        max_length=50,
                        verbose_name="Категория земли",
                    ),
                ),
            ],
            options={
                "verbose_name": "Категория земель",
                "verbose_name_plural": "Категория земель",
            },
        ),
        migrations.CreateModel(
            name="ObjectDescription",
            fields=[
                (
                    "uuid",
                    models.UUIDField(
                        default=uuid.uuid4, primary_key=True, serialize=False
                    ),
                ),
                (
                    "value",
                    models.TextField(
                        blank=True,
                        help_text="Используйте маркдаун",
                        max_length=2500,
                        verbose_name="Описание объекта",
                    ),
                ),
            ],
            options={
                "verbose_name": "Описание объекта",
                "verbose_name_plural": "Описание объекта",
            },
        ),
        migrations.CreateModel(
            name="Ownership",
            fields=[
                (
                    "uuid",
                    models.UUIDField(
                        default=uuid.uuid4, primary_key=True, serialize=False
                    ),
                ),
                (
                    "value",
                    models.CharField(
                        blank=True,
                        help_text="Форма собственности объекта",
                        max_length=50,
                        verbose_name="Форма собственности",
                    ),
                ),
            ],
            options={
                "verbose_name": "Тип собственности",
                "verbose_name_plural": "Тип собственности",
            },
        ),
        migrations.CreateModel(
            name="ReliefArea",
            fields=[
                (
                    "uuid",
                    models.UUIDField(
                        default=uuid.uuid4, primary_key=True, serialize=False
                    ),
                ),
                (
                    "value",
                    models.CharField(
                        blank=True,
                        help_text="Рельеф участка",
                        max_length=255,
                        verbose_name="Рельеф участка",
                    ),
                ),
            ],
            options={
                "verbose_name": "Рельеф участка",
                "verbose_name_plural": "Рельеф участка",
            },
        ),
        migrations.CreateModel(
            name="TypeHouse",
            fields=[
                (
                    "uuid",
                    models.UUIDField(
                        default=uuid.uuid4, primary_key=True, serialize=False
                    ),
                ),
                ("name", models.CharField(blank=True, max_length=100)),
            ],
            options={
                "verbose_name": "Тип объекта",
                "verbose_name_plural": "Тип объекта",
            },
        ),
        migrations.CreateModel(
            name="VillageFences",
            fields=[
                (
                    "uuid",
                    models.UUIDField(
                        default=uuid.uuid4, primary_key=True, serialize=False
                    ),
                ),
                (
                    "value",
                    models.CharField(
                        blank=True,
                        help_text="Ограждения в поселке",
                        max_length=50,
                        verbose_name="Ограждения в поселке",
                    ),
                ),
            ],
            options={
                "verbose_name": "Ограждения в поселке",
                "verbose_name_plural": "Ограждения в поселке",
            },
        ),
        migrations.CreateModel(
            name="WallMaterial",
            fields=[
                (
                    "uuid",
                    models.UUIDField(
                        default=uuid.uuid4, primary_key=True, serialize=False
                    ),
                ),
                (
                    "value",
                    models.CharField(
                        blank=True,
                        help_text="Материал стен",
                        max_length=50,
                        verbose_name="Материал стен",
                    ),
                ),
            ],
            options={
                "verbose_name": "Материал стен",
                "verbose_name_plural": "Материал стен",
            },
        ),
        migrations.CreateModel(
            name="WindowsOrientation",
            fields=[
                (
                    "uuid",
                    models.UUIDField(
                        default=uuid.uuid4, primary_key=True, serialize=False
                    ),
                ),
                (
                    "value",
                    models.CharField(
                        blank=True,
                        help_text="Ориентация окон",
                        max_length=50,
                        verbose_name="Ориентация окон",
                    ),
                ),
            ],
            options={
                "verbose_name": "Ориентация окон",
                "verbose_name_plural": "Ориентация окон",
            },
        ),
    ]
