# Generated by Django 4.2.9 on 2024-01-30 18:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("apps_reobjects", "0003_reobject_reobjectimage_reobjectengineeringservices"),
    ]

    operations = [
        migrations.AlterField(
            model_name="reobjectengineeringservices",
            name="engineering_service",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="engineering_services",
                to="apps_reobjects.engineeringservices",
            ),
        ),
        migrations.AlterField(
            model_name="reobjectengineeringservices",
            name="re_object",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="re_objects",
                to="apps_reobjects.reobject",
            ),
        ),
    ]
