# Generated by Django 4.2.9 on 2024-02-05 11:50

from django.db import migrations
import mdeditor.fields


class Migration(migrations.Migration):
    dependencies = [
        (
            "apps_reobjects",
            "0004_alter_reobjectengineeringservices_engineering_service_and_more",
        ),
    ]

    operations = [
        migrations.AlterField(
            model_name="reobject",
            name="object_description",
            field=mdeditor.fields.MDTextField(
                blank=True, null=True, verbose_name="Описание объекта"
            ),
        ),
    ]
