# Generated by Django 4.2.9 on 2024-02-05 12:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("apps_reobjects", "0006_alter_reobject_place"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="reobject",
            name="place",
        ),
        migrations.AddField(
            model_name="reobject",
            name="coordinates",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="apps_reobjects.coordinates",
                verbose_name="Координаты",
            ),
        ),
    ]
