# Generated by Django 4.2.9 on 2024-02-05 13:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("apps_reobjects", "0007_remove_reobject_place_reobject_coordinates"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="reobject",
            name="coordinates",
        ),
        migrations.AddField(
            model_name="reobject",
            name="place",
            field=models.ForeignKey(
                blank=True,
                help_text="Укажите месторасположение объекта",
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="apps_reobjects.place",
                verbose_name="Адрес",
            ),
        ),
        migrations.AlterField(
            model_name="reobject",
            name="object_description",
            field=models.ForeignKey(
                blank=True,
                help_text="Текст в markdown",
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="apps_reobjects.objectdescription",
                verbose_name="Описание объекта",
            ),
        ),
    ]
