# Generated by Django 4.2.9 on 2024-02-05 14:26

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):
    dependencies = [
        ("apps_reobjects", "0009_remove_place_city_remove_place_coordinates_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="Coordinates",
            fields=[
                (
                    "uuid",
                    models.UUIDField(
                        default=uuid.uuid4, primary_key=True, serialize=False
                    ),
                ),
                (
                    "ydx_latitude",
                    models.FloatField(null=True, verbose_name="Широта(Яндекс)"),
                ),
                (
                    "ydx_longitude",
                    models.FloatField(null=True, verbose_name="Долгота(Яндекс)"),
                ),
                (
                    "re_object",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="coordinates",
                        to="apps_reobjects.reobject",
                    ),
                ),
            ],
            options={
                "verbose_name": "Координаты",
                "verbose_name_plural": "Координаты",
            },
        ),
    ]
