# Generated by Django 4.2.9 on 2024-02-06 08:11

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):
    dependencies = [
        ("apps_reobjects", "0013_remove_place_city_remove_place_coordinates_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="Coordinates",
            fields=[
                (
                    "uuid",
                    models.UUIDField(
                        default=uuid.uuid4, primary_key=True, serialize=False
                    ),
                ),
                (
                    "yandex_latitude",
                    models.FloatField(
                        blank=True, null=True, verbose_name="Широта (Yandex)"
                    ),
                ),
                (
                    "yandex_longitude",
                    models.FloatField(
                        blank=True, null=True, verbose_name="Долгота (Yandex)"
                    ),
                ),
            ],
            options={
                "verbose_name": "Координаты",
                "verbose_name_plural": "Координаты",
            },
        ),
        migrations.AddField(
            model_name="reobject",
            name="coordinates",
            field=models.OneToOneField(
                blank=True,
                help_text="Широта, Долгота",
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="apps_reobjects.coordinates",
                verbose_name="Координаты объекта",
            ),
        ),
    ]
