# Generated by Django 4.2.9 on 2024-02-06 08:50

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("apps_reobjects", "0014_coordinates_reobject_coordinates"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="reobject",
            name="buildings_on_site",
        ),
    ]
