# Generated by Django 4.2.9 on 2024-02-06 09:04

from django.db import migrations
import mdeditor.fields


class Migration(migrations.Migration):
    dependencies = [
        ("apps_reobjects", "0016_alter_category_uuid_alter_coordinates_uuid_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="reobject",
            name="object_description",
            field=mdeditor.fields.MDTextField(
                blank=True,
                help_text="Текст с форматированием",
                null=True,
                verbose_name="Описание объекта",
            ),
        ),
    ]
