# Generated by Django 4.2.9 on 2024-02-06 09:07

from django.db import migrations
import mdeditor.fields


class Migration(migrations.Migration):
    dependencies = [
        ("apps_reobjects", "0017_alter_reobject_object_description"),
    ]

    operations = [
        migrations.AlterField(
            model_name="service",
            name="secondary_text",
            field=mdeditor.fields.MDTextField(
                blank=True,
                help_text="Текст с форматированием",
                null=True,
                verbose_name="Текст описание в блоке УСЛУГИ",
            ),
        ),
    ]
