# Generated by Django 4.2.9 on 2024-02-06 10:45

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("apps_reobjects", "0018_alter_service_secondary_text"),
    ]

    operations = [
        migrations.AddField(
            model_name="reobject",
            name="name",
            field=models.TextField(
                blank=True,
                help_text="Адрес",
                max_length=255,
                null=True,
                verbose_name="Название объекта",
            ),
        ),
    ]
