# Generated by Django 4.2.9 on 2024-02-09 10:25

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("apps_reobjects", "0021_alter_category_uuid_alter_coordinates_uuid_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="reobject",
            name="buildings_of_villages",
        ),
    ]
