# Generated by Django 4.2.9 on 2024-02-09 10:57

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("apps_reobjects", "0023_rename_value_engineeringservices_name"),
    ]

    operations = [
        migrations.AddField(
            model_name="engineeringservices",
            name="short_text",
            field=models.TextField(
                blank=True,
                help_text="Hапример: '4.4 кВт - 15 кВт' ",
                null=True,
                verbose_name="Короткое описание",
            ),
        ),
        migrations.AddField(
            model_name="engineeringservices",
            name="tag",
            field=models.CharField(
                blank=True,
                help_text="внесите метку для более удобного визуального поиска, например id поселка, или '4.4 кВт - 15 кВт'",
                max_length=50,
                null=True,
                verbose_name="tag",
            ),
        ),
        migrations.AddField(
            model_name="engineeringservices",
            name="text",
            field=models.TextField(
                blank=True,
                help_text="Hапример: 'На дом площадью менее 150 м2 от 4.4 кВт (включено в стоимость дома) и на дома более 150 м2 от 5,5 кВт (включено в стоимость дома) с возможностью увеличения до 15 кВт (35 000 руб. за кВт)' ",
                null=True,
                verbose_name="Полное описание описание",
            ),
        ),
    ]
