# Generated by Django 4.2.9 on 2024-02-09 16:37

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("apps_reobjects", "0025_repair_reobject_distance_cad_reobject_price_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="reobject",
            name="yandex_map_link",
            field=models.TextField(
                blank=True,
                help_text="скопируйте ссылку iframe из браузера и вставьте в это поле",
                null=True,
                verbose_name="Ссылка на YandexMap",
            ),
        ),
        migrations.AddField(
            model_name="reobject",
            name="you_tube_link",
            field=models.TextField(
                blank=True,
                help_text="скопируйте ссылку из браузера и вставьте в это поле",
                null=True,
                verbose_name="Ссылка на YouTube",
            ),
        ),
    ]
