# Generated by Django 4.2.9 on 2024-02-09 18:59

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):
    dependencies = [
        ("apps_reobjects", "0027_reobject_ceiling_height_reobject_date_sale_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="Balcony",
            fields=[
                (
                    "uuid",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("name", models.CharField(blank=True, max_length=100)),
            ],
            options={
                "verbose_name": "Тип балкона/лоджии",
                "verbose_name_plural": "Тип балкона/лоджии",
            },
        ),
        migrations.AddField(
            model_name="reobject",
            name="balcony",
            field=models.ForeignKey(
                blank=True,
                help_text="Выберите из списка, или создайте новое '+'",
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="apps_reobjects.balcony",
                verbose_name="Тип балкона/лоджии",
            ),
        ),
    ]
