# Generated by Django 4.2.9 on 2024-02-09 19:11

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):
    dependencies = [
        ("apps_reobjects", "0028_balcony_reobject_balcony"),
    ]

    operations = [
        migrations.CreateModel(
            name="Driveways",
            fields=[
                (
                    "uuid",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("name", models.CharField(blank=True, max_length=100)),
            ],
            options={
                "verbose_name": "Подъездные пути",
                "verbose_name_plural": "Подъездные пути",
            },
        ),
        migrations.AddField(
            model_name="reobject",
            name="driveways",
            field=models.ForeignKey(
                blank=True,
                help_text="Выберите из списка, или создайте новое '+'",
                null=True,
                on_delete=django.db.models.deletion.RESTRICT,
                to="apps_reobjects.driveways",
                verbose_name="Подъездные пути",
            ),
        ),
    ]
