# Generated by Django 4.2.9 on 2024-02-12 20:10

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):
    dependencies = [
        ("apps_reobjects", "0030_areaofmeasurement_reobject_land_area_measurement"),
    ]

    operations = [
        migrations.CreateModel(
            name="ReObjectPlanModel",
            fields=[
                (
                    "uuid",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("image", models.FileField(upload_to="reobjects/plans/")),
                (
                    "re_object",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="reobjectplans",
                        to="apps_reobjects.reobject",
                    ),
                ),
            ],
            options={
                "verbose_name": "Планировка объекта",
                "verbose_name_plural": "Планировки объектов",
            },
        ),
    ]
