# Generated by Django 4.2.9 on 2024-02-12 20:33

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("apps_reobjects", "0031_reobjectplanmodel"),
    ]

    operations = [
        migrations.AddField(
            model_name="reobject",
            name="visible_on_site",
            field=models.BooleanField(
                blank=True, null=True, verbose_name="Отображать на сайте"
            ),
        ),
    ]
