# Generated by Django 4.2.9 on 2024-02-12 20:53

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):
    dependencies = [
        ("apps_reobjects", "0032_reobject_visible_on_site"),
    ]

    operations = [
        migrations.CreateModel(
            name="WindowMaterial",
            fields=[
                (
                    "uuid",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        blank=True,
                        help_text="Материал окон",
                        max_length=50,
                        verbose_name="Материал окон",
                    ),
                ),
            ],
            options={
                "verbose_name": "Материал окон",
                "verbose_name_plural": "Материал окон",
            },
        ),
        migrations.AlterField(
            model_name="reobject",
            name="id",
            field=models.IntegerField(blank=True, null=True, verbose_name="ID объекта"),
        ),
        migrations.AddField(
            model_name="reobject",
            name="window_material",
            field=models.ForeignKey(
                blank=True,
                help_text="Выберете значение из списка, или создайте новое '+'",
                null=True,
                on_delete=django.db.models.deletion.RESTRICT,
                to="apps_reobjects.windowmaterial",
                verbose_name="Материал окон",
            ),
        ),
    ]
