# Generated by Django 4.2.9 on 2024-02-12 21:02

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):
    dependencies = [
        ("apps_reobjects", "0033_windowmaterial_alter_reobject_id_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="SalesMethod",
            fields=[
                (
                    "uuid",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        blank=True,
                        help_text="Способ продажи(нужно пояснение расширить)",
                        max_length=50,
                        verbose_name="Способ продажи",
                    ),
                ),
            ],
            options={
                "verbose_name": "Способ продажи",
                "verbose_name_plural": "Способ продажи",
            },
        ),
        migrations.AddField(
            model_name="reobject",
            name="sales_method",
            field=models.ForeignKey(
                blank=True,
                help_text="Выберете значение из списка, или создайте новое '+'",
                null=True,
                on_delete=django.db.models.deletion.RESTRICT,
                to="apps_reobjects.salesmethod",
                verbose_name="Способ продажи",
            ),
        ),
    ]
