# Generated by Django 4.2.9 on 2024-02-20 18:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("apps_reobjects", "0035_reobjectemployee"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="reobject",
            name="land_area",
        ),
        migrations.RemoveField(
            model_name="reobject",
            name="total_area",
        ),
        migrations.AddField(
            model_name="reobject",
            name="area_flat",
            field=models.FloatField(
                blank=True,
                help_text="Площадь квартиры общая, кв. м",
                null=True,
                verbose_name="Площадь квартиры общая, кв. м",
            ),
        ),
        migrations.AddField(
            model_name="reobject",
            name="area_house",
            field=models.FloatField(
                blank=True,
                help_text="Площадь дома, кв. м",
                null=True,
                verbose_name="Площадь дома, кв. м",
            ),
        ),
        migrations.AddField(
            model_name="reobject",
            name="area_plot",
            field=models.FloatField(
                blank=True,
                help_text="Площадь участка, кв. м",
                null=True,
                verbose_name="Площадь участка, кв. м",
            ),
        ),
        migrations.AddField(
            model_name="reobject",
            name="area_room",
            field=models.FloatField(
                blank=True,
                help_text="Для коммунальных квартир",
                null=True,
                verbose_name="Площадь комнаты, кв. м",
            ),
        ),
        migrations.AddField(
            model_name="reobject",
            name="buildings_on_plot",
            field=models.TextField(
                blank=True,
                help_text="Введите текст",
                null=True,
                verbose_name="Строения на участке",
            ),
        ),
        migrations.AddField(
            model_name="reobject",
            name="date_foundation",
            field=models.DateField(
                blank=True,
                help_text="введите дату",
                null=True,
                verbose_name="Год постройки дома",
            ),
        ),
        migrations.AddField(
            model_name="reobject",
            name="metro",
            field=models.TextField(
                blank=True,
                help_text="Академическая, 5 мин. Пешком, 15 мин. транспорт",
                null=True,
                verbose_name="Метро",
            ),
        ),
        migrations.AddField(
            model_name="reobject",
            name="place",
            field=models.TextField(
                blank=True,
                help_text="Введите текст",
                max_length=255,
                null=True,
                verbose_name="Адрес",
            ),
        ),
        migrations.AlterField(
            model_name="reobject",
            name="fencing",
            field=models.ForeignKey(
                blank=True,
                help_text="Выберите из списка, или создайте новое '+'",
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="apps_reobjects.fencing",
                verbose_name="Ограждение участка",
            ),
        ),
        migrations.AlterField(
            model_name="reobject",
            name="foundation",
            field=models.ForeignKey(
                blank=True,
                help_text="Блоки, Лента, Плита ... Выберите из списка, или создайте новое '+'",
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="apps_reobjects.foundation",
                verbose_name="Фундамент",
            ),
        ),
        migrations.AlterField(
            model_name="reobject",
            name="name",
            field=models.TextField(
                blank=True,
                help_text="Название объекта",
                max_length=255,
                null=True,
                verbose_name="Название объекта",
            ),
        ),
        migrations.AlterField(
            model_name="reobject",
            name="relief_area",
            field=models.ForeignKey(
                blank=True,
                help_text="Выберите из списка, или создайте новое '+'",
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="apps_reobjects.reliefarea",
                verbose_name="Рельеф участка",
            ),
        ),
        migrations.AlterField(
            model_name="reobject",
            name="type_house",
            field=models.ForeignKey(
                blank=True,
                help_text="Вторичное жилье, Новостройка... Выберите из списка, или создайте новое '+'",
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="apps_reobjects.typehouse",
                verbose_name="Тип объекта",
            ),
        ),
        migrations.AlterField(
            model_name="reobject",
            name="village_fences",
            field=models.ForeignKey(
                blank=True,
                help_text="Выберите из списка, или создайте новое '+'",
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="apps_reobjects.villagefences",
                verbose_name="Ограждение поселка",
            ),
        ),
        migrations.AlterField(
            model_name="reobject",
            name="wall_material",
            field=models.ForeignKey(
                blank=True,
                help_text="Кирпич, Панель, Пеноблок ... Выберите из списка, или создайте новое '+'",
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="apps_reobjects.wallmaterial",
                verbose_name="Материал стен",
            ),
        ),
    ]
