# Generated by Django 4.2.9 on 2024-02-20 20:14

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):
    dependencies = [
        (
            "apps_reobjects",
            "0036_remove_reobject_land_area_remove_reobject_total_area_and_more",
        ),
    ]

    operations = [
        migrations.CreateModel(
            name="Lift",
            fields=[
                (
                    "uuid",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "value",
                    models.CharField(
                        blank=True,
                        help_text="Лифт",
                        max_length=300,
                        verbose_name="Лифт",
                    ),
                ),
            ],
            options={
                "verbose_name": "Лифт",
                "verbose_name_plural": "Лифт",
            },
        ),
        migrations.AlterField(
            model_name="reobject",
            name="balcony",
            field=models.ForeignKey(
                blank=True,
                help_text="Выберите из списка, или создайте новое '+'",
                null=True,
                on_delete=django.db.models.deletion.RESTRICT,
                to="apps_reobjects.balcony",
                verbose_name="Тип балкона/лоджии",
            ),
        ),
        migrations.AlterField(
            model_name="reobject",
            name="category",
            field=models.ForeignKey(
                blank=True,
                help_text="Дом, Квартира, Участок",
                null=True,
                on_delete=django.db.models.deletion.RESTRICT,
                to="apps_reobjects.category",
                verbose_name="Категория объекта",
            ),
        ),
        migrations.AlterField(
            model_name="reobject",
            name="coordinates",
            field=models.OneToOneField(
                blank=True,
                help_text="Широта, Долгота",
                null=True,
                on_delete=django.db.models.deletion.RESTRICT,
                to="apps_reobjects.coordinates",
                verbose_name="Координаты объекта",
            ),
        ),
        migrations.AlterField(
            model_name="reobject",
            name="fencing",
            field=models.ForeignKey(
                blank=True,
                help_text="Выберите из списка, или создайте новое '+'",
                null=True,
                on_delete=django.db.models.deletion.RESTRICT,
                to="apps_reobjects.fencing",
                verbose_name="Ограждение участка",
            ),
        ),
        migrations.AlterField(
            model_name="reobject",
            name="foundation",
            field=models.ForeignKey(
                blank=True,
                help_text="Блоки, Лента, Плита ... Выберите из списка, или создайте новое '+'",
                null=True,
                on_delete=django.db.models.deletion.RESTRICT,
                to="apps_reobjects.foundation",
                verbose_name="Фундамент",
            ),
        ),
        migrations.AlterField(
            model_name="reobject",
            name="land_area_measurement",
            field=models.ForeignKey(
                blank=True,
                help_text="Выберите из списка, или создайте новое '+'",
                null=True,
                on_delete=django.db.models.deletion.RESTRICT,
                to="apps_reobjects.areaofmeasurement",
                verbose_name="Единицы измерения площади участка",
            ),
        ),
        migrations.AlterField(
            model_name="reobject",
            name="land_category",
            field=models.ForeignKey(
                blank=True,
                help_text="Коммерческая",
                null=True,
                on_delete=django.db.models.deletion.RESTRICT,
                to="apps_reobjects.landcategory",
                verbose_name="Категория земель",
            ),
        ),
        migrations.AlterField(
            model_name="reobject",
            name="ownership",
            field=models.ForeignKey(
                blank=True,
                help_text="От собственника, Ипотека, и.т.д",
                null=True,
                on_delete=django.db.models.deletion.RESTRICT,
                to="apps_reobjects.ownership",
                verbose_name="Собственность",
            ),
        ),
        migrations.AlterField(
            model_name="reobject",
            name="relief_area",
            field=models.ForeignKey(
                blank=True,
                help_text="Выберите из списка, или создайте новое '+'",
                null=True,
                on_delete=django.db.models.deletion.RESTRICT,
                to="apps_reobjects.reliefarea",
                verbose_name="Рельеф участка",
            ),
        ),
        migrations.AlterField(
            model_name="reobject",
            name="repair",
            field=models.ForeignKey(
                blank=True,
                help_text="Выберите из списка, или создайте новое '+'",
                null=True,
                on_delete=django.db.models.deletion.RESTRICT,
                to="apps_reobjects.repair",
                verbose_name="Ремонт",
            ),
        ),
        migrations.AlterField(
            model_name="reobject",
            name="village_fences",
            field=models.ForeignKey(
                blank=True,
                help_text="Выберите из списка, или создайте новое '+'",
                null=True,
                on_delete=django.db.models.deletion.RESTRICT,
                to="apps_reobjects.villagefences",
                verbose_name="Ограждение поселка",
            ),
        ),
        migrations.AlterField(
            model_name="reobject",
            name="wall_material",
            field=models.ForeignKey(
                blank=True,
                help_text="Кирпич, Панель, Пеноблок ... Выберите из списка, или создайте новое '+'",
                null=True,
                on_delete=django.db.models.deletion.RESTRICT,
                to="apps_reobjects.wallmaterial",
                verbose_name="Материал стен",
            ),
        ),
        migrations.AlterField(
            model_name="reobject",
            name="windows_orientation",
            field=models.ForeignKey(
                blank=True,
                help_text="Запад, Север, Восток, и.т.д",
                null=True,
                on_delete=django.db.models.deletion.RESTRICT,
                to="apps_reobjects.windowsorientation",
                verbose_name="Ориентация окон",
            ),
        ),
        migrations.AddField(
            model_name="reobject",
            name="lift",
            field=models.ForeignKey(
                blank=True,
                help_text="да, нет, 2, 3, 4",
                null=True,
                on_delete=django.db.models.deletion.RESTRICT,
                to="apps_reobjects.lift",
                verbose_name="Лифт",
            ),
        ),
    ]
