# Generated by Django 4.2.9 on 2024-02-20 20:22

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):
    dependencies = [
        (
            "apps_reobjects",
            "0037_lift_alter_reobject_balcony_alter_reobject_category_and_more",
        ),
    ]

    operations = [
        migrations.CreateModel(
            name="ApproveUsage",
            fields=[
                (
                    "uuid",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "value",
                    models.TextField(
                        blank=True,
                        help_text="Разрешенное использование",
                        verbose_name="Разрешенное использование",
                    ),
                ),
            ],
            options={
                "verbose_name": "Разрешенное использование",
                "verbose_name_plural": "Разрешенное использование",
            },
        ),
        migrations.AddField(
            model_name="reobject",
            name="approve_usage",
            field=models.ForeignKey(
                blank=True,
                help_text="Разрешенное использование",
                null=True,
                on_delete=django.db.models.deletion.RESTRICT,
                to="apps_reobjects.approveusage",
                verbose_name="Разрешенное использование",
            ),
        ),
    ]
