# Generated by Django 4.2.9 on 2024-02-26 20:55

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):
    dependencies = [
        ("apps_reobjects", "0040_alter_reobjectemployee_options_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="VisibleOnSite",
            fields=[
                (
                    "uuid",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "value",
                    models.CharField(
                        blank=True,
                        help_text="Введите текст",
                        max_length=50,
                        verbose_name="Страница отображения",
                    ),
                ),
            ],
            options={
                "verbose_name": "Страница отображения",
                "verbose_name_plural": "Страница отображения",
            },
        ),
        migrations.CreateModel(
            name="ReObjectVisibleOnSite",
            fields=[
                (
                    "uuid",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "page",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="pages",
                        to="apps_reobjects.visibleonsite",
                        verbose_name="Страница сайта",
                    ),
                ),
                (
                    "re_object",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="reobjectsite",
                        to="apps_reobjects.reobject",
                    ),
                ),
            ],
            options={
                "verbose_name": "Отображение на сайте",
                "verbose_name_plural": "Отображение на сайте",
            },
        ),
    ]
