# Generated by Django 4.2.9 on 2024-02-26 21:37

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("apps_reobjects", "0042_rename_page_reobjectvisibleonsite_visible_on_site"),
    ]

    operations = [
        migrations.RenameField(
            model_name="reobjectvisibleonsite",
            old_name="visible_on_site",
            new_name="display_pages",
        ),
    ]
