# Generated by Django 4.2.9 on 2024-03-03 15:36

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        (
            "apps_reobjects",
            "0043_rename_visible_on_site_reobjectvisibleonsite_display_pages",
        ),
    ]

    operations = [
        migrations.AddField(
            model_name="visibleonsite",
            name="type_value",
            field=models.CharField(
                blank=True,
                help_text="Введите текст латиницей в формате 'word-word-word'",
                max_length=255,
                null=True,
                verbose_name="Псевдоним названия страниц",
            ),
        ),
        migrations.AlterField(
            model_name="visibleonsite",
            name="value",
            field=models.CharField(
                blank=True,
                help_text="Введите текст",
                max_length=255,
                null=True,
                verbose_name="Страница отображения",
            ),
        ),
    ]
