# Generated by Django 4.2.9 on 2024-03-03 15:54

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("apps_reobjects", "0044_visibleonsite_type_value_alter_visibleonsite_value"),
    ]

    operations = [
        migrations.AlterField(
            model_name="reobject",
            name="id",
            field=models.IntegerField(default=0, verbose_name="ID объекта"),
        ),
    ]
