# Generated by Django 4.2.9 on 2024-03-03 15:56

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("apps_reobjects", "0047_alter_reobject_id"),
    ]

    operations = [
        migrations.AlterField(
            model_name="reobject",
            name="id",
            field=models.PositiveBigIntegerField(
                unique=True, verbose_name="ID объекта"
            ),
        ),
    ]
