# Generated by Django 4.2.9 on 2024-03-05 21:55

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("apps_reobjects", "0048_alter_reobject_id"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="reobjectplanmodel",
            options={
                "verbose_name": "План объекта",
                "verbose_name_plural": "Планы объекта",
            },
        ),
    ]
