# Generated by Django 4.2.9 on 2024-03-05 22:42

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("apps_reobjects", "0049_alter_reobjectplanmodel_options"),
    ]

    operations = [
        migrations.RenameField(
            model_name="reobjectimage",
            old_name="re_object",
            new_name="objectModel",
        ),
    ]
