# Generated by Django 4.2.9 on 2024-03-12 20:22

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("apps_reobjects", "0051_rename_re_object_reobjectplanmodel_objectmodel"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="reobject",
            name="coordinates",
        ),
        migrations.AlterField(
            model_name="reobject",
            name="area_flat",
            field=models.FloatField(
                blank=True, null=True, verbose_name="Общая площадь, кв. м"
            ),
        ),
        migrations.AlterField(
            model_name="reobject",
            name="area_plot",
            field=models.FloatField(
                blank=True,
                help_text="Единицы измерения, Площадь участка, кв. м, сотки - выбираются выше",
                null=True,
                verbose_name="Площадь участка",
            ),
        ),
        migrations.AlterField(
            model_name="reobject",
            name="kitchen_area",
            field=models.FloatField(
                blank=True,
                help_text="Площадь кухни в помещении",
                null=True,
                verbose_name="Площадь кухни, кв. м",
            ),
        ),
        migrations.AlterField(
            model_name="reobject",
            name="living_area",
            field=models.FloatField(
                blank=True,
                help_text="Жилая площадь в помещении",
                null=True,
                verbose_name="Жилая площадь, кв. м",
            ),
        ),
    ]
