# Generated by Django 4.2.9 on 2024-03-12 20:24

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("apps_reobjects", "0053_remove_reobject_date_foundation"),
    ]

    operations = [
        migrations.AddField(
            model_name="reobject",
            name="date_foundation",
            field=models.PositiveIntegerField(
                blank=True,
                help_text="введите дату",
                null=True,
                verbose_name="Год постройки дома",
            ),
        ),
    ]
