# Generated by Django 4.2.9 on 2024-03-12 20:38

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("apps_reobjects", "0054_reobject_date_foundation"),
    ]

    operations = [
        migrations.AddField(
            model_name="reobjectimage",
            name="order",
            field=models.PositiveIntegerField(
                blank=True, help_text="введите число", null=True, verbose_name="Порядок"
            ),
        ),
    ]
