# Generated by Django 4.2.9 on 2024-03-13 19:52

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):
    dependencies = [
        ("apps_reobjects", "0056_reobjectplanmodel_order"),
    ]

    operations = [
        migrations.CreateModel(
            name="WC",
            fields=[
                (
                    "uuid",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "value",
                    models.CharField(
                        blank=True,
                        help_text="Санузел",
                        max_length=255,
                        verbose_name="Санузел",
                    ),
                ),
            ],
            options={
                "verbose_name": "Санузел",
                "verbose_name_plural": "Санузел",
            },
        ),
    ]
