# Generated by Django 4.2.9 on 2024-03-13 19:56

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("apps_reobjects", "0057_wc"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="reobject",
            name="wc",
        ),
    ]
