# Generated by Django 4.2.9 on 2024-03-13 19:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("apps_reobjects", "0058_remove_reobject_wc"),
    ]

    operations = [
        migrations.AddField(
            model_name="reobject",
            name="wc",
            field=models.ForeignKey(
                blank=True,
                help_text="Выберите из списка, или создайте новое '+'",
                null=True,
                on_delete=django.db.models.deletion.RESTRICT,
                to="apps_reobjects.wc",
                verbose_name="Санузел",
            ),
        ),
    ]
