# Generated by Django 4.2.9 on 2024-03-14 21:04

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):
    dependencies = [
        ("apps_reobjects", "0059_reobject_wc"),
    ]

    operations = [
        migrations.CreateModel(
            name="ReObjectClose",
            fields=[
                (
                    "uuid",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "close_re_object",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="reobjectclose",
                        to="apps_reobjects.reobject",
                        verbose_name="Похожий объект",
                    ),
                ),
                (
                    "re_object",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="reobjectbase",
                        to="apps_reobjects.reobject",
                    ),
                ),
            ],
            options={
                "verbose_name": "Похожие объекты",
                "verbose_name_plural": "Похожие объекты",
            },
        ),
    ]
