# Generated by Django 4.2.9 on 2024-01-30 18:36

from django.db import migrations, models
import mdeditor.fields
import uuid


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Post",
            fields=[
                (
                    "uuid",
                    models.UUIDField(
                        default=uuid.uuid4, primary_key=True, serialize=False
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        blank=True,
                        help_text="Введите текст",
                        max_length=255,
                        verbose_name="Название поста",
                    ),
                ),
                ("body", mdeditor.fields.MDTextField(blank=True, null=True)),
            ],
            options={
                "verbose_name": "Пост",
                "verbose_name_plural": "Посты",
            },
        ),
    ]
