# Generated by Django 4.2.9 on 2024-03-05 22:01

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("apps_blog", "0007_alter_post_options_alter_posttagsmodel_post"),
    ]

    operations = [
        migrations.RenameField(
            model_name="postimagemodel",
            old_name="post",
            new_name="objectModel",
        ),
    ]
