# Generated by Django 4.2.9 on 2024-01-24 07:34

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):
    dependencies = [
        ("apps_users", "0002_group_employeeprofilemodel"),
    ]

    operations = [
        migrations.CreateModel(
            name="EmployeeProfileAvatarModel",
            fields=[
                (
                    "uuid",
                    models.UUIDField(
                        default=uuid.uuid4, primary_key=True, serialize=False
                    ),
                ),
                ("image", models.FileField(upload_to="avatars/")),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="apps_users.employeeprofilemodel",
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
        ),
    ]
