# Generated by Django 4.2.9 on 2024-01-24 07:43

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("apps_users", "0003_employeeprofileavatarmodel"),
    ]

    operations = [
        migrations.RenameField(
            model_name="employeeprofileavatarmodel",
            old_name="user",
            new_name="profile",
        ),
    ]
