# Generated by Django 4.2.9 on 2024-01-27 15:54

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):
    dependencies = [
        ("apps_users", "0004_rename_user_employeeprofileavatarmodel_profile"),
    ]

    operations = [
        migrations.CreateModel(
            name="ReObjectModel",
            fields=[
                (
                    "uuid",
                    models.UUIDField(
                        default=uuid.uuid4, primary_key=True, serialize=False
                    ),
                ),
                ("name", models.CharField(max_length=255)),
            ],
            options={
                "verbose_name": "Объект недвижимости",
                "verbose_name_plural": "Объекты недвижимости",
            },
        ),
        migrations.AlterModelOptions(
            name="employeeprofileavatarmodel",
            options={
                "verbose_name": "Аватар Сотрудника",
                "verbose_name_plural": "Аватары Сотрудников",
            },
        ),
        migrations.AddField(
            model_name="employeeprofilemodel",
            name="phone_number",
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name="employeeprofilemodel",
            name="position",
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name="employeeprofilemodel",
            name="telegram_link",
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name="employeeprofilemodel",
            name="whatsapp_link",
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name="employeeprofilemodel",
            name="work_email",
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AlterField(
            model_name="employeeprofileavatarmodel",
            name="profile",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="avatars",
                to="apps_users.employeeprofilemodel",
            ),
        ),
        migrations.CreateModel(
            name="ReObjectImageModel",
            fields=[
                (
                    "uuid",
                    models.UUIDField(
                        default=uuid.uuid4, primary_key=True, serialize=False
                    ),
                ),
                ("image", models.FileField(upload_to="avatars/")),
                (
                    "re_object",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="reobject_images",
                        to="apps_users.reobjectmodel",
                    ),
                ),
            ],
            options={
                "verbose_name": "Картинка Объекта недвижимости",
                "verbose_name_plural": "Картинки Объектов недвижимости",
            },
        ),
    ]
