# Generated by Django 4.2.9 on 2024-02-22 10:56

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("apps_users", "0012_remove_employeeprofilemodel_position_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="employeeprofilemodel",
            name="location",
            field=models.TextField(blank=True, null=True, verbose_name="Район, Районы"),
        ),
    ]
