# Generated by Django 4.2.9 on 2024-03-05 22:26

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("apps_users", "0013_employeeprofilemodel_location"),
    ]

    operations = [
        migrations.RenameField(
            model_name="employeeprofileavatarmodel",
            old_name="profile",
            new_name="objectModel",
        ),
    ]
