# Generated by Django 4.2.9 on 2024-02-07 18:28

from django.db import migrations


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("apps_reviews", "0002_alter_reviewimagemodel_review"),
    ]

    operations = [
        migrations.CreateModel(
            name="ReviewProxy",
            fields=[],
            options={
                "verbose_name": "Отзыв",
                "verbose_name_plural": "Отзывы",
                "proxy": True,
                "indexes": [],
                "constraints": [],
            },
            bases=("apps_reviews.review",),
        ),
    ]
