# Generated by Django 4.2.9 on 2024-01-28 13:24

from django.db import migrations


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("apps_users", "0005_reobjectmodel_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="EmployeeProfileProxyModel",
            fields=[],
            options={
                "verbose_name": "Сотрудник",
                "verbose_name_plural": "Сотрудники",
                "proxy": True,
                "indexes": [],
                "constraints": [],
            },
            bases=("apps_users.employeeprofilemodel",),
        ),
    ]
