# Generated by Django 4.2.9 on 2024-02-07 18:28

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Application",
            fields=[
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "uuid",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "text",
                    models.TextField(
                        blank=True,
                        help_text="Просто текст",
                        null=True,
                        verbose_name="Текст вопроса",
                    ),
                ),
                (
                    "applicant",
                    models.CharField(
                        blank=True,
                        help_text="например: Андреева Любовь, Кох И.С.",
                        max_length=1000,
                        null=True,
                        verbose_name="Имя покупателя полностью",
                    ),
                ),
                (
                    "contact",
                    models.TextField(
                        blank=True,
                        help_text="Контактные данные",
                        null=True,
                        verbose_name="Контактные данные",
                    ),
                ),
            ],
            options={
                "verbose_name": "Заявка",
                "verbose_name_plural": "Заявки",
            },
        ),
        migrations.CreateModel(
            name="ApplicationImageModel",
            fields=[
                (
                    "uuid",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("image", models.FileField(upload_to="applications/")),
                (
                    "application",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="applicationimages",
                        to="apps_applications.application",
                    ),
                ),
            ],
            options={
                "verbose_name": "Фото к заявке",
                "verbose_name_plural": "Фото к заявке",
            },
        ),
    ]
