# Generated by Django 4.2.9 on 2024-02-08 14:07

from django.db import migrations, models
import django.db.models.deletion
import mdeditor.fields
import uuid


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Village",
            fields=[
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "uuid",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("id", models.IntegerField(blank=True, null=True)),
                (
                    "name",
                    models.TextField(
                        blank=True,
                        help_text="Адрес",
                        null=True,
                        verbose_name="Название объекта",
                    ),
                ),
                (
                    "object_description",
                    mdeditor.fields.MDTextField(
                        blank=True,
                        help_text="Текст с форматированием",
                        null=True,
                        verbose_name="Описание объекта",
                    ),
                ),
                (
                    "you_tube_link",
                    models.TextField(
                        blank=True,
                        help_text="скопируйте ссылку из браузера и вставьте в это поле",
                        null=True,
                        verbose_name="Ссылка на YouTube",
                    ),
                ),
                (
                    "yandex_map_link",
                    models.TextField(
                        blank=True,
                        help_text="скопируйте ссылку iframe из браузера и вставьте в это поле",
                        null=True,
                        verbose_name="Ссылка на YandexMap",
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="VillagePlanModel",
            fields=[
                (
                    "uuid",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("image", models.FileField(upload_to="village/plans/")),
                (
                    "village",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="villageplans",
                        to="apps_village.village",
                    ),
                ),
            ],
            options={
                "verbose_name": "План поселка",
                "verbose_name_plural": "Планы поселков",
            },
        ),
        migrations.CreateModel(
            name="VillageImageModel",
            fields=[
                (
                    "uuid",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("image", models.FileField(upload_to="village/images/")),
                (
                    "village",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="villageimages",
                        to="apps_village.village",
                    ),
                ),
            ],
            options={
                "verbose_name": "Фото поселка",
                "verbose_name_plural": "Фото поселков",
            },
        ),
    ]
