# Generated by Django 4.2.9 on 2024-02-09 09:42

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):
    dependencies = [
        ("apps_village", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="AreaOfPlotMeasurement",
            fields=[
                (
                    "uuid",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        blank=True,
                        max_length=255,
                        null=True,
                        verbose_name="Название единицы измерения",
                    ),
                ),
            ],
            options={
                "verbose_name": "Единица измерения",
                "verbose_name_plural": "Единицы измерения",
            },
        ),
        migrations.AddField(
            model_name="village",
            name="area_of_plot",
            field=models.FloatField(
                blank=True,
                help_text="введите знaчение, например '1.2' ",
                null=True,
                verbose_name="Площадь одного участка",
            ),
        ),
        migrations.AddField(
            model_name="village",
            name="distance_CAD",
            field=models.FloatField(
                blank=True,
                help_text="введите знaчение в КМ, например '1.2' ",
                null=True,
                verbose_name="Расстояние до кад",
            ),
        ),
        migrations.AddField(
            model_name="village",
            name="area_of_plot_measurement",
            field=models.ForeignKey(
                blank=True,
                help_text="Выберете значение из списка",
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="apps_village.areaofplotmeasurement",
                verbose_name="Единица измерения",
            ),
        ),
    ]
