# Generated by Django 4.2.9 on 2024-02-09 09:54

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):
    dependencies = [
        ("apps_village", "0002_areaofplotmeasurement_village_area_of_plot_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="CategoryLandPlot",
            fields=[
                (
                    "uuid",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        blank=True,
                        max_length=255,
                        null=True,
                        verbose_name="Категория земель",
                    ),
                ),
            ],
            options={
                "verbose_name": "Категория земель",
                "verbose_name_plural": "Категория земель",
            },
        ),
        migrations.AlterField(
            model_name="village",
            name="area_of_plot_measurement",
            field=models.ForeignKey(
                blank=True,
                help_text="Выберете значение из списка",
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="apps_village.areaofplotmeasurement",
                verbose_name="Единица измерения площади одного участка",
            ),
        ),
        migrations.AddField(
            model_name="village",
            name="category_land",
            field=models.ForeignKey(
                blank=True,
                help_text="Выберете значение из списка",
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="apps_village.categorylandplot",
                verbose_name="Категория земель участков",
            ),
        ),
    ]
