# Generated by Django 4.2.9 on 2024-02-09 09:59

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):
    dependencies = [
        ("apps_village", "0003_categorylandplot_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="ReliefAreaPlot",
            fields=[
                (
                    "uuid",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "value",
                    models.CharField(
                        blank=True,
                        help_text="Рельеф участка",
                        max_length=255,
                        verbose_name="Рельеф участка",
                    ),
                ),
            ],
            options={
                "verbose_name": "Рельеф участка",
                "verbose_name_plural": "Рельеф участка",
            },
        ),
        migrations.AlterField(
            model_name="village",
            name="area_of_plot_measurement",
            field=models.ForeignKey(
                blank=True,
                help_text="Выберете значение из списка, или создайте новое '+'",
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="apps_village.areaofplotmeasurement",
                verbose_name="Единица измерения площади одного участка",
            ),
        ),
        migrations.AlterField(
            model_name="village",
            name="category_land",
            field=models.ForeignKey(
                blank=True,
                help_text="Выберете значение из списка, или создайте новое '+'",
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="apps_village.categorylandplot",
                verbose_name="Категория земель участков",
            ),
        ),
        migrations.AddField(
            model_name="village",
            name="relief_area_plot",
            field=models.ForeignKey(
                blank=True,
                help_text="Выберете значение из списка, или создайте новое '+'",
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="apps_village.reliefareaplot",
                verbose_name="Рельеф участков",
            ),
        ),
    ]
