# Generated by Django 4.2.9 on 2024-02-09 10:09

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):
    dependencies = [
        ("apps_village", "0004_reliefareaplot_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="FencingVillage",
            fields=[
                (
                    "uuid",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        blank=True,
                        help_text="Введите текстовое значение",
                        max_length=255,
                        null=True,
                        verbose_name="Ограждение поселка",
                    ),
                ),
            ],
            options={
                "verbose_name": "Ограждение поселка",
                "verbose_name_plural": "Ограждение поселка",
            },
        ),
        migrations.CreateModel(
            name="SecurityVillage",
            fields=[
                (
                    "uuid",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        blank=True,
                        help_text="Введите текстовое значение",
                        max_length=255,
                        verbose_name="Охрана поселка",
                    ),
                ),
            ],
            options={
                "verbose_name": "Охрана поселка",
                "verbose_name_plural": "Охрана поселка",
            },
        ),
        migrations.RemoveField(
            model_name="reliefareaplot",
            name="value",
        ),
        migrations.AddField(
            model_name="reliefareaplot",
            name="name",
            field=models.CharField(
                blank=True,
                help_text="Рельеф участка",
                max_length=255,
                null=True,
                verbose_name="Рельеф участка",
            ),
        ),
        migrations.AddField(
            model_name="village",
            name="fencing_village",
            field=models.ForeignKey(
                blank=True,
                help_text="Выберете значение из списка, или создайте новое '+'",
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="apps_village.fencingvillage",
                verbose_name="Ограждение поселка",
            ),
        ),
        migrations.AddField(
            model_name="village",
            name="security_village",
            field=models.ForeignKey(
                blank=True,
                help_text="Выберете значение из списка, или создайте новое '+'",
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="apps_village.securityvillage",
                verbose_name="Охрана поселка",
            ),
        ),
    ]
