# Generated by Django 4.2.9 on 2024-02-09 10:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("apps_reobjects", "0022_remove_reobject_buildings_of_villages"),
        ("apps_village", "0005_fencingvillage_securityvillage_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="village",
            name="area_of_houses",
            field=models.TextField(
                blank=True,
                help_text="введите знaчение, например '100 - 200' ",
                null=True,
                verbose_name="Площадь домов в кв.м",
            ),
        ),
        migrations.AddField(
            model_name="village",
            name="buildings_of_villages",
            field=models.PositiveIntegerField(
                blank=True,
                help_text="Количество домов в поселке",
                null=True,
                verbose_name="Количество домов в поселке",
            ),
        ),
        migrations.AddField(
            model_name="village",
            name="foundation",
            field=models.ForeignKey(
                blank=True,
                help_text="Выберете значение из списка, или создайте новое '+'",
                null=True,
                on_delete=django.db.models.deletion.RESTRICT,
                to="apps_reobjects.foundation",
                verbose_name="Фундамент домов",
            ),
        ),
        migrations.AddField(
            model_name="village",
            name="wall_material",
            field=models.ForeignKey(
                blank=True,
                help_text="Выберете значение из списка, или создайте новое '+'",
                null=True,
                on_delete=django.db.models.deletion.RESTRICT,
                to="apps_reobjects.wallmaterial",
                verbose_name="Материал стен домов в поселке",
            ),
        ),
        migrations.AlterField(
            model_name="village",
            name="area_of_plot_measurement",
            field=models.ForeignKey(
                blank=True,
                help_text="Выберете значение из списка, или создайте новое '+'",
                null=True,
                on_delete=django.db.models.deletion.RESTRICT,
                to="apps_village.areaofplotmeasurement",
                verbose_name="Единица измерения площади одного участка",
            ),
        ),
        migrations.AlterField(
            model_name="village",
            name="category_land",
            field=models.ForeignKey(
                blank=True,
                help_text="Выберете значение из списка, или создайте новое '+'",
                null=True,
                on_delete=django.db.models.deletion.RESTRICT,
                to="apps_village.categorylandplot",
                verbose_name="Категория земель участков",
            ),
        ),
        migrations.AlterField(
            model_name="village",
            name="fencing_village",
            field=models.ForeignKey(
                blank=True,
                help_text="Выберете значение из списка, или создайте новое '+'",
                null=True,
                on_delete=django.db.models.deletion.RESTRICT,
                to="apps_village.fencingvillage",
                verbose_name="Ограждение поселка",
            ),
        ),
        migrations.AlterField(
            model_name="village",
            name="relief_area_plot",
            field=models.ForeignKey(
                blank=True,
                help_text="Выберете значение из списка, или создайте новое '+'",
                null=True,
                on_delete=django.db.models.deletion.RESTRICT,
                to="apps_village.reliefareaplot",
                verbose_name="Рельеф участков",
            ),
        ),
        migrations.AlterField(
            model_name="village",
            name="security_village",
            field=models.ForeignKey(
                blank=True,
                help_text="Выберете значение из списка, или создайте новое '+'",
                null=True,
                on_delete=django.db.models.deletion.RESTRICT,
                to="apps_village.securityvillage",
                verbose_name="Охрана поселка",
            ),
        ),
    ]
