# Generated by Django 4.2.9 on 2024-02-09 16:10

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):
    dependencies = [
        ("apps_reobjects", "0024_engineeringservices_short_text_and_more"),
        (
            "apps_village",
            "0006_village_area_of_houses_village_buildings_of_villages_and_more",
        ),
    ]

    operations = [
        migrations.CreateModel(
            name="EngineeringVillageServices",
            fields=[],
            options={
                "verbose_name": "Инженерные сети",
                "verbose_name_plural": "Инженерные сети",
                "proxy": True,
                "indexes": [],
                "constraints": [],
            },
            bases=("apps_reobjects.engineeringservices",),
        ),
        migrations.CreateModel(
            name="VillageEngineeringServices",
            fields=[
                (
                    "uuid",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "engineering_service",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="village_engineering_services",
                        to="apps_reobjects.engineeringservices",
                    ),
                ),
                (
                    "re_object",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="villages",
                        to="apps_village.village",
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
        ),
    ]
