# Generated by Django 4.2.9 on 2024-02-12 20:53

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("apps_village", "0007_engineeringvillageservices_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="village",
            name="buildings_on_plot",
            field=models.TextField(
                blank=True,
                help_text="Опишите строения на участке",
                null=True,
                verbose_name="Строения на участке",
            ),
        ),
        migrations.AddField(
            model_name="village",
            name="visible_on_site",
            field=models.BooleanField(
                blank=True, null=True, verbose_name="Отображать на сайте"
            ),
        ),
        migrations.AlterField(
            model_name="village",
            name="id",
            field=models.IntegerField(blank=True, null=True, verbose_name="ID посёлка"),
        ),
    ]
