# Generated by Django 4.2.9 on 2024-02-26 19:49

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        (
            "apps_village",
            "0008_village_buildings_on_plot_village_visible_on_site_and_more",
        ),
    ]

    operations = [
        migrations.RenameField(
            model_name="villageengineeringservices",
            old_name="re_object",
            new_name="village",
        ),
    ]
