# Generated by Django 4.2.9 on 2024-02-26 20:23

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):
    dependencies = [
        ("apps_users", "0013_employeeprofilemodel_location"),
        ("apps_village", "0009_rename_re_object_villageengineeringservices_village"),
    ]

    operations = [
        migrations.CreateModel(
            name="VillageEmployee",
            fields=[
                (
                    "uuid",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "employee",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="villageagents",
                        to="apps_users.employeeprofilemodel",
                    ),
                ),
                (
                    "village",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="villageemployees",
                        to="apps_village.village",
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
        ),
    ]
