# Generated by Django 4.2.9 on 2024-03-12 19:47

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("apps_village", "0013_rename_village_villageplanmodel_objectmodel"),
    ]

    operations = [
        migrations.AddField(
            model_name="village",
            name="price",
            field=models.PositiveBigIntegerField(
                blank=True,
                help_text="введите знaчение в РУБ, например '1000000' ",
                null=True,
                verbose_name="Цена",
            ),
        ),
    ]
