# Generated by Django 4.2.9 on 2024-03-12 19:50

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("apps_village", "0014_village_price"),
    ]

    operations = [
        migrations.AddField(
            model_name="village",
            name="place",
            field=models.TextField(
                blank=True,
                help_text="Введите текст",
                max_length=255,
                null=True,
                verbose_name="Адрес",
            ),
        ),
        migrations.AlterField(
            model_name="village",
            name="name",
            field=models.TextField(
                blank=True,
                help_text="Введите текст",
                null=True,
                verbose_name="Название объекта",
            ),
        ),
    ]
