# Generated by Django 4.2.9 on 2024-03-12 20:27

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("apps_village", "0015_village_place_alter_village_name"),
    ]

    operations = [
        migrations.AlterField(
            model_name="village",
            name="buildings_of_villages",
            field=models.PositiveIntegerField(
                blank=True,
                help_text="Количество объектов в поселке",
                null=True,
                verbose_name="Количество объектов в поселке",
            ),
        ),
    ]
