# Generated by Django 4.2.9 on 2024-03-12 20:33

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("apps_village", "0016_alter_village_buildings_of_villages"),
    ]

    operations = [
        migrations.AddField(
            model_name="village",
            name="infra",
            field=models.TextField(
                blank=True,
                help_text="Введите текст",
                null=True,
                verbose_name="Инфраструктура",
            ),
        ),
    ]
