# Generated by Django 4.2.9 on 2024-03-12 21:08

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("apps_village", "0017_village_infra"),
    ]

    operations = [
        migrations.AddField(
            model_name="villageimagemodel",
            name="order",
            field=models.PositiveIntegerField(
                blank=True, help_text="введите число", null=True, verbose_name="Порядок"
            ),
        ),
        migrations.AddField(
            model_name="villageplanmodel",
            name="order",
            field=models.PositiveIntegerField(
                blank=True, help_text="введите число", null=True, verbose_name="Порядок"
            ),
        ),
    ]
