# Generated by Django 4.2.9 on 2024-03-17 11:35

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):
    dependencies = [
        ("apps_reobjects", "0060_reobjectclose"),
        ("apps_village", "0018_villageimagemodel_order_villageplanmodel_order"),
    ]

    operations = [
        migrations.CreateModel(
            name="ReObjectInVillages",
            fields=[
                (
                    "uuid",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "close_re_object",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="reobjectinvilages",
                        to="apps_reobjects.reobject",
                        verbose_name="Объект",
                    ),
                ),
                (
                    "village",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="reobjectbase",
                        to="apps_village.village",
                    ),
                ),
            ],
            options={
                "verbose_name": "Объекты в поселке",
                "verbose_name_plural": "Объекты в поселке",
            },
        ),
    ]
