# Generated by Django 4.2.9 on 2024-03-17 11:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("apps_village", "0019_reobjectinvillages"),
    ]

    operations = [
        migrations.AlterField(
            model_name="reobjectinvillages",
            name="village",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="villagebase",
                to="apps_village.village",
            ),
        ),
    ]
