# Generated by Django 4.2.9 on 2024-03-17 11:50

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("apps_village", "0020_alter_reobjectinvillages_village"),
    ]

    operations = [
        migrations.RenameField(
            model_name="reobjectinvillages",
            old_name="close_re_object",
            new_name="re_object_in_villages",
        ),
    ]
