# Generated by Django 4.2.9 on 2024-02-07 18:28

from django.db import migrations


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("apps_applications", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="ApplicationProxy",
            fields=[],
            options={
                "verbose_name": "Заявки",
                "verbose_name_plural": "Заявки",
                "proxy": True,
                "indexes": [],
                "constraints": [],
            },
            bases=("apps_applications.application",),
        ),
    ]
