# Generated by Django 4.2.9 on 2024-02-07 14:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("apps_reviews", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="reviewimagemodel",
            name="review",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="reviewimages",
                to="apps_reviews.review",
            ),
        ),
    ]
