# Generated by Django 4.2.9 on 2024-02-13 17:23

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("apps_reviews", "0002_alter_reviewimagemodel_review"),
    ]

    operations = [
        migrations.AddField(
            model_name="review",
            name="date_sale",
            field=models.DateField(
                blank=True,
                help_text="Выберите дату публикации",
                null=True,
                verbose_name="Дата публикации",
            ),
        ),
    ]
