# Generated by Django 4.2.9 on 2024-03-05 21:55

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("apps_reviews", "0003_review_date_sale"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="reviewimagemodel",
            options={
                "verbose_name": "Фото к ревью",
                "verbose_name_plural": "Фото к ревью",
            },
        ),
    ]
