# Generated by Django 4.2.9 on 2024-03-05 21:56

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("apps_reviews", "0004_alter_reviewimagemodel_options"),
    ]

    operations = [
        migrations.RenameField(
            model_name="reviewimagemodel",
            old_name="review",
            new_name="objectModel",
        ),
    ]
