# Generated by Django 4.2.9 on 2024-03-05 22:24

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("admin_service", "0001_initial"),
    ]

    operations = [
        migrations.DeleteModel(
            name="Service",
        ),
    ]
